add_product_main/urls.py
from add_product_main import views as add_product_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = 'add_product_main'

urlpatterns = [
    path('<str:username>/polozka/pridanie/', add_product_views.pridaj_polozku, name='user_pridaj_polozku'),
    path('<str:username>/doprava/pridanie/delete/<int:transport_id>/', add_product_views.delete_transport, name='user_delete_transport'),
    path('<str:username>/transportloc/<int:transportloc_id>/delete/', add_product_views.delete_transport_loc, name='delete_transport_loc'),
    path('<str:username>/doprava/<str:nazov_produktu>/select/<int:transport_id>/', add_product_views.select_transport, name='user_select_transport'),
    path('<str:username>/doprava/<str:nazov_produktu>/deselect/<int:transport_id>/', add_product_views.deselect_transport, name='user_deselect_transport'),
    path('<str:username>/doprava/pridanie/', add_product_views.pridaj_dopravu, name='user_pridaj_dopravu'),
    path('<str:username>/polozka/<str:nazov_produktu>/', add_product_views.zobraz_polozku, name='user_zobraz_polozku'),
    path('<str:username>/polozka/<str:nazov_produktu>/<int:anchor>/', add_product_views.zobraz_polozku, name='user_zobraz_polozku'),
    path('<str:username>/polozka/<str:nazov_produktu>/delete/<int:cena_id>/', add_product_views.delete_cena, name='user_delete_cena'),
    path('<str:username>/delete_picture/<int:product_id>/', add_product_views.delete_picture, name='delete_picture'),
    path('<str:username>/polozka/<str:nazov_produktu>/add_picture/', add_product_views.add_picture, name='add_picture'),
] 

# Add the following line to handle media files
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
#api/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import ClusterAPIView, UserLocationsViewSet, StateProvincePobockaCountViewSet

app_name = 'api'

router = DefaultRouter()
router.register(r'locations', UserLocationsViewSet, basename='locations')
router.register(r'regions', StateProvincePobockaCountViewSet, basename='state-province-count')

urlpatterns = [
    path('', include(router.urls)),
    path('clusters/', ClusterAPIView.as_view(), name='cluster-api'),  # Use path directly
]

chat_general/urls.py
from chat_general import views as chat_general_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from search import views as search_views

app_name = 'chat_general'

urlpatterns = [
    # Redirect URL pattern
    path('<str:username>/chats/<str:sender>/', chat_general_views.redirect_to_chat_general, name='redirect_to_chat_general'),

    path('<str:username>/chats/', chat_general_views.chat_general, name='user_chat_general'),
    path('<str:username>/chats/<str:sender>/', chat_general_views.chat_general, name='user_chat_general_with_sender'),
    path('<str:username>/chats/<str:sender>/send_message', chat_general_views.send_message_in_general_chat, name='send_message_in_general_chat'),

    path('<str:username>/chats_mobile/', chat_general_views.chat_general_mobile, name='chat_general_mobile'),
    path('<str:username>/chats_mobile/<str:sender>/', chat_general_views.chat_general_mobile, name='chat_general_mobile_with_sender'),
] 

edit_profile/urls.py
#edit_profile/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from edit_profile import views as edit_profile_views

app_name = 'edit_profile'

urlpatterns = [
    path('<str:username>/settings/edit', edit_profile_views.profile_editing, name='user_profile_editing'),
    path('accounts/become-seller', edit_profile_views.update_seller_status, name='update_seller_status'),
    path('<str:username>/offshores', edit_profile_views.add_pobocka, name='add_pobocka'),
    path('<str:username>/delete/pobocka/<int:pobocka_id>/', edit_profile_views.delete_pobocka, name='delete_pobocka'),
]

farmeris/urls.py
#farmeris/urls.py

from allauth.account.views import EmailView
from allauth.account.views import email as allauth_email_view
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.utils.decorators import method_decorator
from django.views.generic import RedirectView
from django.views.i18n import set_language
from email_verification.decorators import email_verification_required
from email_verification.views import CustomEmailView
from login_app import views as login_views
from login_app.views import CustomConfirmEmailView


@method_decorator(email_verification_required, name='dispatch')
class ProtectedEmailView(EmailView):
    pass

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('set_language/', set_language, name='set_language'),
    path('handle_unverified_email/', login_views.handle_unverified_email, name='handle_unverified_email'),
    re_path(r'^account/confirm-email/(?P<key>[-:\w]+)/$', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    path('accounts/resend-confirmation/', login_views.resend_confirmation_email, name='resend_confirmation_email'),
    # path('accounts/email/', email_verification_required(allauth_email_view), name='account_email'),
    path('accounts/email/', login_required(ProtectedEmailView.as_view()), name='account_email'),
    path('email-verification/', include('email_verification.urls')),
    #path('register/', login_views.register, name='register'),
    #path('mapka/', login_views.mapka, name='mapka'),
    #path('login/', login_views.login, name='login'),
    path('privacy-policy/', login_views.privacy_policy, name='privacy_policy'),
    path('accounts/', include('allauth.urls')),
    # path('', RedirectView.as_view(url='/main/')), # root URL redirect
    path('', include('main.urls')),
    path('', include('texts.urls', namespace='texts')),
    path('', include('notes.urls', namespace='notes')),
    path('', include('search.urls', namespace='search')),
    path('', include('map.urls', namespace='map')),
    path('', include('tagmanager.urls', namespace='tagmanager')),
    path('', include('login_app.urls', namespace='login_app')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include('user_profile.urls', namespace='user_profile')),
    path('', include('add_product_main.urls', namespace='add_product_main')),
    path('', include('edit_profile.urls', namespace='edit_profile')),
    path('', include('chat_polozka.urls', namespace='chat_polozka')),
    path('', include('obrazky.urls', namespace='obrazky')),
    path('', include('chat_general.urls', namespace='chat_general')),
    path('email-verification/', include('email_verification.urls')),
    # URL pattern for serving static files in development
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from search import views as search_views

app_name = 'search'

urlpatterns = [
    path('search/', search_views.search, name='user_search'),
    path('search/users/', search_views.search2, name='user_search2'),
]

user_profile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from user_profile import views

app_name = 'user_profile'

urlpatterns = [
    path('<str:username>/', views.user_profile, name='user_profile'),
    path('<str:username>/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('<str:username>/delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
] 

user_profile/models.py
from django.db import models

'''
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.user.username
        
class ProductAddFeed(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    namefeed = models.CharField(max_length=255)
    textfeed = models.TextField()

    def __str__(self):
        return self.name
'''

user_profile/forms.py
from django import forms
from login_app.models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = []

user_profile/views.py
#user_profile/views.py

from datetime import datetime

import pytz
from add_product_main.models import Cena, Polozka, PolozkaTransport, Transport
from allauth.account.models import EmailAddress
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Prefetch, Q
from django.http import Http404, HttpResponse, HttpResponseForbidden, QueryDict
from django.shortcuts import get_object_or_404, redirect, render
from login_app.models import UserProfile
from edit_profile.models import Pobocka
from user_profile.forms import UserProfileForm


def user_profile(request, username):
    user = get_object_or_404(User, username=username)
    user_profile = UserProfile.objects.get(user__username=username)
    transport_list = Transport.objects.filter(user_profile=user_profile)
    products = Polozka.objects.filter(user_profile__user__username=username).order_by('-created_at')
    pobocky = Pobocka.objects.filter(user_profile=user_profile)
    # For anonymous users (not logged in), set polozka_transport_list to an empty list
    polozka_transport_list = []
    polozka_transport_dict = {}
    
    if request.user.is_authenticated:
        polozka_transport_list = PolozkaTransport.objects.filter(polozka__in=products, transport__user_profile__user=request.user)
        # Create a dictionary with polozka as key and polozka_transport as value
        polozka_transport_dict = {polozka_transport.polozka: polozka_transport for polozka_transport in polozka_transport_list}
        
    # Prefetch the related cena objects for each product to avoid additional queries
    products = products.prefetch_related(
        Prefetch('ceny', queryset=Cena.objects.filter(user_profile=user_profile), to_attr='ceny_list'),
        Prefetch('polozkatransport_set', queryset=PolozkaTransport.objects.select_related('transport').filter(polozka__user_profile=user_profile), to_attr='transport_list')
    )
    
    #search
    query = request.GET.get('query')
    if query:
        products = products.filter(nazov_produktu__icontains=query)
    #search
    #pagination
    if request.user.is_authenticated:
        default_pagination = user_profile.pagination_preference
    else:
        default_pagination = 10  # or any default value you want for non-logged in users
        
    items_per_page = int(request.GET.get('items_per_page', default_pagination))

    paginator = Paginator(products, items_per_page)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    query_params = request.GET.copy()
    query_params.pop('page', None)

    #saved pagination for user
    if request.user.is_authenticated and items_per_page != default_pagination:
        user_profile.pagination_preference = items_per_page
        user_profile.save()
    #end of pagination

    # #feeding user info from the backend
    # location_parts = [
    #     part for part in [
    #         user_profile.state_province,
    #         user_profile.street_address,
    #         user_profile.zip_postal_code,
    #         user_profile.city,
    #         user_profile.country
    #     ] if part  # This filters out any None or empty string values
    # ]
    # location_string = ', '.join(location_parts)

    # Company information preparation
    company_info_parts = list(filter(None, [
        user_profile.company_name,
        f"IČO: {user_profile.company_id_number}" if user_profile.company_id_number else None,
        f"DIČ: {user_profile.tax_id_number}" if user_profile.tax_id_number else None,
        f"IČ DPH: {user_profile.vat_number}" if user_profile.vat_number else None,
        f"Sidlo firmy: {user_profile.company_address}" if user_profile.company_address else None
    ]))

    context = {
        'username': username,
        'user_profile': user_profile,
        'products': products,
        'pobocky': pobocky,
        'items_per_page': items_per_page,
        'polozka_transport_dict': polozka_transport_dict,
        'query_params': query_params.urlencode(),
        'transport_list': transport_list,
        'company_info_parts': company_info_parts,
    }
    return render(request, 'user_profile.html', context)

@login_required(login_url='user_profile:user_profile')
def user_profile_edit(request, username):
    if request.user.username != username:
        # Redirect or handle unauthorized access
        return HttpResponseForbidden()
        
    user = get_object_or_404(User, username=username)
    user_profile = UserProfile.objects.get(user__username=username)
    products = Polozka.objects.filter(user_profile__user__username=username)
    polozka_transport_list = []
    polozka_transport_dict = {}
    email_verified = EmailAddress.objects.filter(user=request.user, verified=True).exists()

    #pagination
    if request.user.is_authenticated:
        default_pagination = user_profile.pagination_preference
    else:
        default_pagination = 10  # or any default value you want for non-logged in users
        
    items_per_page = int(request.GET.get('items_per_page', default_pagination)) - 1 

    paginator = Paginator(products, items_per_page)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    query_params = request.GET.copy()
    query_params.pop('page', None)
    #saved pagination for user
    if request.user.is_authenticated and items_per_page + 1 != default_pagination:
        user_profile.pagination_preference = items_per_page + 1
        user_profile.save()
    #end of pagination
    
    #profile = get_object_or_404(UserProfile, user=user)
    context = {
        'username': username,
        'user_profile': user_profile,
        'products': products,
        'items_per_page': items_per_page + 1,
        'email_verified': email_verified,
        #'profile': profile,
        'current_view_name': 'user_profile_edit',
    }
    return render(request, 'user_profile_edit.html', context)

@login_required(login_url='user_profile:user_profile')
def delete_product(request, username, product_id):
    # Ensure that the user is the owner of the product
    if request.user.username != username:
        return HttpResponseForbidden()

    # Retrieve the product and check if it belongs to the user
    product = get_object_or_404(Polozka, id=product_id, user_profile__user__username=username)

    # Perform the actual deletion
    product.delete()

    # Redirect back to the user profile page
    #return redirect('user_profile:user_profile', username=username)
    # Get the 'next' URL from the query parameters
    next_url = request.GET.get('next', 'user_profile:user_profile')  # Redirect to user profile by default if 'next' is not provided

    # Redirect back to the appropriate URL
    return redirect(next_url, username=username)

user_profile/templates/display_products.html
<!DOCTYPE html>
<html lang="en" data-theme="{{ user_profile.theme }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Vypis z databazky:</h1>.

    {% for product in products %}
        <p>{{ product.name }}</p>
        <p>{{ product.info }}</p>
        <!-- Add more fields as needed -->
    {% endfor %}

    <p>nefunguje, ze? Ha</p>
</body>
</html>

user_profile/templates/displayer.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Output Product Feed</title>
</head>
<body>
    <h1>Output Product Feed</h1>
    {% if product_feeds %}
        <ul>
            {% for product_feed in product_feeds %}
                <li>
                    <h3>{{ product_feed.namefeed }}</h3>
                    <p>{{ product_feed.textfeed }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No product feeds found.</p>
    {% endif %}
</body>
</html>

user_profile/templates/extra_css.html
{% extends 'polozka.html' %}

{% block extra_css %}
    <link href="{% static 'css/polozka_pridanie.css' %}" rel="stylesheet">
{% endblock %}

{% block polozka %}
    <!-- Content specific to 'polozka_pridanie.html' -->
{% endblock %}

user_profile/templates/feeder.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Add Product Feed</title>
</head>
<body>
    <h1>Add Product Feed</h1>
    <form action="{% url 'feeding_data:feeder' %}" method="post">
        {% csrf_token %}
        <label for="namefeed">Name:</label>
        <input type="text" id="namefeed" name="namefeed"><br><br>
        <label for="textfeed">Text:</label>
        <textarea id="textfeed" name="textfeed"></textarea><br><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

user_profile/templates/polozka_newy.html
{% load static %}
{% load tz %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'css/polozka.css' %}" rel="stylesheet" media="screen">
    {% block extra_css %}{% endblock %}
    <!--<link href="../static/css/pridaj_polozku.css" rel="stylesheet" media="screen">
  --> 
    <meta charset="UTF-8">
    <!--{% block pagerefresh %}{% endblock %}
    <meta http-equiv="refresh" content="60">--> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Farma market</title>
    <link rel="icon" type="image/png" href="pics/favicon/x.png">
    <link rel="stylesheet" href="/static/css/tabler-icons.css">
</head>


<body>
  <nav class="sidebar">
    {% include 'user_profile_display.html' %}  
    <ul>
        <!--<li><a href="main.html">Home</a></li>-->
        <li><a href="{% url 'search:user_search' %}">Search</a></li>
        <li><a href="{% url 'chat_general:user_chat_general' username=user_profile.user.username %}">Chat</a></li>
        <li><a href="{% url 'user_profile:user_profile_edit' username=user_profile.user.username %}">Add your offers</a></li>
        <li><a href="{% url 'add_product_main:user_pridaj_dopravu' username=user_profile.user.username %}">My transport</a></li>
    </ul>
  </nav>
  <div class="wrapper">
    {% block polozka %}{% endblock %}
  
    <footer>
      {% include 'footer_content.html' %}
    </footer>
  </div>
</body>
</html>

user_profile/templates/polozka_profile_view.html
{% load custom_filters %}
{% load static i18n %}

<!--<link href="{% static 'css/polozka_profile_viewx.css' %}" rel="stylesheet" media="screen">-->
  <div class="product">
    {% if request.user == product.user_profile.user %}
      <div class="remove-button-icon">
        <a class="user-profile-delete-btn" href="{% url 'user_profile:delete_product' username=user_profile.user.username product_id=product.id %}?next={{ request.path }}" onclick="return confirmDelete('{{ product.nazov_produktu }}')">
          <div class="minus-icon"></div>
        </a>
      </div>
    {% endif %}
    
    <a class="product-click" href="{% url 'add_product_main:user_zobraz_polozku' username=product.user_profile.user.username nazov_produktu=nazov_produktu %}">
      <div class="product-click"></div>
    </a>
    
    <div class="product-pic">
      {% if polozka.image %}
        <img src="{{ polozka.image.url }}" alt="{{ polozka.nazov_produktu }}">
      {% else %}
        <p>{% trans "No picture available" %}</p>
      {% endif %}
    </div>
    <div class="product-nazov-container">
      <div class="product-nazov">
        <!--JAJKA M size 63g/piece grassfed organic non-gmo-->
        <h3>{{ nazov_produktu }}</h3>
      </div>
    </div>
    <a href="{% url 'user_profile:user_profile' username=polozka.user_profile.user.username %}" target="_blank" class="polozka-owner-a">
      <div class="product-nazov-owner">
        <span>{{ polozka.user_profile.user }}</span>
      </div>
    </a>
    <div class="product-dostupnost">
      <span>{{ polozka.availability_status }}</span>
    </div>
    <div class="product-vlastnosti-container">
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">
        {% for cena in polozka.ceny.all|slice:":1" %}
          {% with price=cena.price amount=cena.amount|floatformat unit=cena.unit %}
            <p class="product-vlastnosti-container-cena">
              {{ price }}/
              {% if amount and amount != "1" %}
                {{ amount }}
              {% endif %}
              {{ unit }}
            </p>
          {% endwith %}
        {% empty %}
          {% trans "No price" %}
        {% endfor %}
      </button>
      <div class="product-vlastnosti-popup1">
        <div class="product-vlastnosti-popup-column1">
          {% for cena in polozka.ceny.all|slice:":5" %}
            <p class="product-vlastnosti-popup-text1">
              <span>
                {{ cena.price|decimal_places:2 }}{{ cena.currency }}/{{ cena.unit }}
              </span>
            </p>
          {% endfor %}
          {% if product.ceny.count > 5 %}
            <p class="product-vlastnosti-popup-text1">
              <span>
                <p>{% trans "And more..." %}</p>
              </span>
            </p>
          {% endif %}
        </div>
      </div>
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">{% trans "Transport" %}</button>
      <div class="product-vlastnosti-popup2">
        <div class="product-vlastnosti-popup-column2">
          <p class="product-vlastnosti-popup-text2">{% trans "Function under the development" %}</p>
        </div>
        <div class="product-vlastnosti-popup-column2">
          <p class="product-vlastnosti-popup-text2"></p>
        </div>
      </div>
      <!--
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">Kvalita</button>
      <div class="product-vlastnosti-popup3">
        <div class="product-vlastnosti-popup-column3">
          <p class="product-vlastnosti-popup-text3">Function under the development</p>
        </div>
        <div class="product-vlastnosti-popup-column3">
          <p class="product-vlastnosti-popup-text3"></p>
        </div>
      </div>
      -->
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">
        {% comment %}
        <!-- _/5 <img src="{% static 'images/review_star.svg' %}" alt="{% trans 'review_star' %}" class="star-icon"> -->
        {% endcomment %}
      </button>
      <div class="product-vlastnosti-popup4">
        <div class="product-vlastnosti-popup-column4">
          <p class="product-vlastnosti-popup-text4">{% trans "Function under the development" %}</p>
        </div>
        <div class="product-vlastnosti-popup-column4">
          <p class="product-vlastnosti-popup-text4"></p>
        </div>
      </div>
    </div>
  </div>


<script src="{% static 'js/polozka_delete_confirmation.js' %}"></script>

user_profile/templates/polozka_profile_view_add.html
{% load custom_filters %}
{% load static %}




<div class="product">
    <a class="product-create-abs product-create-abs2" href="{% url 'add_product_main:user_pridaj_polozku' username=user_profile.user.username %}">
      <div class="product-create-abs container-plusko-click">
          {% include "icons/plus_raw.html" %}
      </div>
    </a>
    <div class="product-pic">
        <p>Pridaj obrázok</p>
    </div>
    <div class="product-nazov-container">
      <div class="product-nazov">
        <h3>Názov produktu</h3>
      </div>
    </div>
      <div class="product-nazov-owner">
        <span>{{ username }}</span>
      </div>
    <div class="product-vlastnosti-container">
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">
        Cena
      </button>
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">Doprava</button>
      <!--
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">Kvalita</button>
      -->
      <button class="product-vlastnosti-buttonx" data-popup="product-vlastnosti-popup1">
        <!-- _/5 <img src="{% static 'images/review_star.svg' %}" alt="review_star" class="star-icon"> -->
        Okres
      </button>
    </div>
</div>


<script src="{% static 'js/polozka_delete_confirmation.js' %}"></script>

user_profile/templates/user_profile_edit.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% if global_css_styles %}
    {% for css_file in global_css_styles %}
        <link rel="stylesheet" href="{% static css_file %}">
    {% endfor %}
  {% endif %}
  <link href="{% static 'css/user_profile_edit.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/user_profile2.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/search2.css' %}" rel="stylesheet">
  <link href="{% static 'css/polozka_profile_view.css' %}" rel="stylesheet" media="screen">
  <link href="{% static 'css/polozka_profile_view2.css' %}" rel="stylesheet" media="screen">
  <!--<link href="../static/css/user_profile.css" rel="stylesheet" media="screen">-->
  {% block extra_css_edit %}{% endblock %}
  {% block extra_css_polozka_view %}{% endblock %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% trans "Farmeris" %}</title>
  <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="/static/css/tabler-icons.css">
</head>


<body>
  <main>
    {% include 'search_header.html' %}
    {% include 'sidebar.html' %}

    {% include 'sidebar-btn.html' %}
    <div class="green-main-bg">
      <div class="blue-main-bg">
        
        {% block content %}
          <div class="user">
            <div class="user-container">
              {% blocktrans %}<h1>Profile of a user:</h1>{% endblocktrans %}
              <h1>{{ username }}</h1>
            </div>
            <br>
            <!-- THIS REUIRES CHANGES/AINT WORKING YET -->
            {% if not email_verified %}
              <div class="alert alert-warning" role="alert">
                {% trans "Your email address is not verified yet. Please check your inbox (and spam folder) for the verification email, or " %}
                <a href="{% url 'account_email' %}">{% trans "click here" %}</a>
                {% trans "to send the verification email again. You can also contact administrator at priec@farmeris.sk" %}
              </div>
            {% endif %}
            {% if not user.userprofile.is_trusted %}
              <h3>{% trans "This profile was not yet verified. Contact administrator at priec@farmeris.sk for permissions to add offers as trusted company. Right now your offers are visible only in unfiltered environment." %}</h3>
            {% endif %}
          </div>
        {% endblock %}
        <!--
        {% if request.user.username == username or request.user.is_superuser %}
          <a class="edit_user_profile-a" href="{% url 'user_profile:user_profile_edit' username=user_profile.user.username %}"><button class="edit_user_profile2">Editovat profil</button></a>
        {% endif %}
        -->
        {% if request.user.is_authenticated and username == request.user.username %}
          {% include 'polozka_profile_view_add.html' with username=request.user.username %}
        {% endif %}
        {% for product in products %}
          {% include 'polozka_profile_view.html' with username=request.user.username nazov_produktu=product.nazov_produktu polozka=product %}
        {% endfor %}
        
        {% include 'pagination.html' %}
      </div>
    </div>
    <footer>
      {% include 'footer_content.html' %}
    </footer>
  </main>
</body>
</html>

user_profile/templates/user_profile_edit_doprava.html
{% load static %}
{% block extra_css_edit %}
    <link href="{% static 'css/user_profile_edit_doparavax.css' %}" rel="stylesheet">
{% endblock %}


<div class="product-create">
    <a href="{% url 'add_product_main:user_pridaj_dopravu' username=user_profile.user.username %}" target="_blank">
        <div class="product-create-doprava">
            {% include "icons/transport2_icon.html" %}
        </div>
    </a>
    <a href="{% url 'edit_profile:user_profile_editing' username=user_profile.user.username %}" target="_blank">
        <div class="product-create-info">
            {% include "icons/settings.html" %}
        </div>
    </a>
</div>