api/urls.py
#api/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import ClusterAPIView, UserLocationsViewSet, StateProvincePobockaCountViewSet

app_name = 'api'

router = DefaultRouter()
router.register(r'locations', UserLocationsViewSet, basename='locations')
router.register(r'regions', StateProvincePobockaCountViewSet, basename='state-province-count')

urlpatterns = [
    path('', include(router.urls)),
    path('clusters/', ClusterAPIView.as_view(), name='cluster-api'),  # Use path directly
]

chat_general/urls.py
from chat_general import views as chat_general_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from search import views as search_views

app_name = 'chat_general'

urlpatterns = [
    # Redirect URL pattern
    path('<str:username>/chats/<str:sender>/', chat_general_views.redirect_to_chat_general, name='redirect_to_chat_general'),

    path('<str:username>/chats/', chat_general_views.chat_general, name='user_chat_general'),
    path('<str:username>/chats/<str:sender>/', chat_general_views.chat_general, name='user_chat_general_with_sender'),
    path('<str:username>/chats/<str:sender>/send_message', chat_general_views.send_message_in_general_chat, name='send_message_in_general_chat'),

    path('<str:username>/chats_mobile/', chat_general_views.chat_general_mobile, name='chat_general_mobile'),
    path('<str:username>/chats_mobile/<str:sender>/', chat_general_views.chat_general_mobile, name='chat_general_mobile_with_sender'),
] 

farmeris/urls.py
#farmeris/urls.py

from allauth.account.views import EmailView
from allauth.account.views import email as allauth_email_view
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.utils.decorators import method_decorator
from django.views.generic import RedirectView
from django.views.i18n import set_language
from email_verification.decorators import email_verification_required
from email_verification.views import CustomEmailView
from login_app import views as login_views
from login_app.views import CustomConfirmEmailView


@method_decorator(email_verification_required, name='dispatch')
class ProtectedEmailView(EmailView):
    pass

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('set_language/', set_language, name='set_language'),
    path('handle_unverified_email/', login_views.handle_unverified_email, name='handle_unverified_email'),
    re_path(r'^account/confirm-email/(?P<key>[-:\w]+)/$', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    path('accounts/resend-confirmation/', login_views.resend_confirmation_email, name='resend_confirmation_email'),
    # path('accounts/email/', email_verification_required(allauth_email_view), name='account_email'),
    path('accounts/email/', login_required(ProtectedEmailView.as_view()), name='account_email'),
    path('email-verification/', include('email_verification.urls')),
    #path('register/', login_views.register, name='register'),
    #path('mapka/', login_views.mapka, name='mapka'),
    #path('login/', login_views.login, name='login'),
    path('privacy-policy/', login_views.privacy_policy, name='privacy_policy'),
    path('accounts/', include('allauth.urls')),
    # path('', RedirectView.as_view(url='/main/')), # root URL redirect
    path('', include('main.urls')),
    path('', include('texts.urls', namespace='texts')),
    path('', include('notes.urls', namespace='notes')),
    path('', include('search.urls', namespace='search')),
    path('', include('map.urls', namespace='map')),
    path('', include('tagmanager.urls', namespace='tagmanager')),
    path('', include('login_app.urls', namespace='login_app')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include('user_profile.urls', namespace='user_profile')),
    path('', include('add_product_main.urls', namespace='add_product_main')),
    path('', include('edit_profile.urls', namespace='edit_profile')),
    path('', include('chat_polozka.urls', namespace='chat_polozka')),
    path('', include('obrazky.urls', namespace='obrazky')),
    path('', include('chat_general.urls', namespace='chat_general')),
    path('email-verification/', include('email_verification.urls')),
    # URL pattern for serving static files in development
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from user_profile import views

app_name = 'user_profile'

urlpatterns = [
    path('<str:username>/', views.user_profile, name='user_profile'),
    path('<str:username>/edit/', views.user_profile_edit, name='user_profile_edit'),
    path('<str:username>/delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
] 

chat_general/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class ChatMessageGeneral(models.Model):
    sender_general = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_sender_general')
    recipient_general = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_receiver_general', default=None)
    content_general = models.TextField()
    created_at_general = models.DateTimeField(default=timezone.now)

    def get_role(self, user):
        if user == self.sender_general:
            return 'sender'
        elif user == self.recipient_general:
            return 'recipient'
        return None

    def __str__(self):
        return self.content_general

chat_general/views.py
from datetime import datetime
from itertools import chain
from urllib.parse import urlencode

import pytz
from add_product_main.models import Polozka
from chat_general.models import ChatMessageGeneral
from chat_polozka.models import ChatMessage
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404, HttpResponse, HttpResponseForbidden, QueryDict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from login_app.models import UserProfile
from user_profile.forms import UserProfileForm


@login_required(login_url='user_profile:user_profile')
def chat_general(request, username, sender=None):

    if request.user.username != username:
        return HttpResponseForbidden()

    #user_profile = UserProfile.objects.get(user__username=username)
    query = request.GET.get('query')
    recipient = None

    if query:
        try:
            recipient = User.objects.get(username=query)
        except User.DoesNotExist:
            pass

    user_profile = UserProfile.objects.get(user=request.user)

    chat_messages_general = ChatMessageGeneral.objects.filter(
        Q(sender_general=request.user, recipient_general=recipient) |
        Q(sender_general=recipient, recipient_general=request.user)
    )

    chat_messages = ChatMessage.objects.filter(
        Q(sender=request.user, recipient=recipient) |
        Q(sender=recipient, recipient=request.user)
    )

    #all_messages = list(chat_messages) + list(chat_messages_general)
    #all_messages.sort(key=lambda x: x.timestamp)
    all_messages = [{"type": "general", "message": msg} for msg in chat_messages_general] + [{"type": "chat", "message": msg} for msg in chat_messages]

    received_senders = ChatMessageGeneral.objects.filter(
        recipient_general=request.user
    ).values_list('sender_general__username', flat=True).distinct()
    
    sent_to_senders = ChatMessageGeneral.objects.filter(
        sender_general=request.user
    ).values_list('recipient_general__username', flat=True).distinct()
    senders = list(set(received_senders) | set(sent_to_senders))

    received_from = ChatMessage.objects.filter(recipient=request.user).values_list('sender__username', flat=True).distinct()
    sent_to = ChatMessage.objects.filter(sender=request.user).values_list('recipient__username', flat=True).distinct()
    unique_chat_partners = list(set(received_from) | set(sent_to))

    combined_senders = list(set(senders) | set(unique_chat_partners))


    context = {
        'user_profile': user_profile,
        'chat_messages_general': chat_messages_general,
        'chat_messages': chat_messages,
        'query': query,
        'recipient': recipient,
        'username': username,
        'combined_senders': combined_senders,
        'all_messages': all_messages,
        'current_view_name': 'chat_general',
    }

    return render(request, 'general_chat.html', context)

@login_required(login_url='user_profile:user_profile')
def send_message_in_general_chat(request, username, sender):
    if request.method == 'POST':
        message_content = request.POST.get('message')
        sender_general = get_object_or_404(User, username=username)
        recipient_general = get_object_or_404(User, username=sender)
        ChatMessageGeneral.objects.create(
            sender_general=sender_general,
            recipient_general=recipient_general,
            content_general=message_content
        )

        redirect_url = reverse('chat_general:user_chat_general_with_sender', kwargs={
            'username': username,
            'sender': sender,
        })
        #query_string = urlencode({'query': sender})
        #redirect_url += f'{query_string}'

        return redirect(redirect_url)
    else:
        raise Http404('Invalid request method.')

def redirect_to_chat_general(request, username, sender):
    redirect_url = f"/{username}/chats/?query={sender}"
    return redirect(redirect_url)


#mobile chat
@login_required(login_url='user_profile:user_profile')
def chat_general_mobile(request, username, sender=None):
    if request.user.username != username:
        return HttpResponseForbidden()

    #user_profile = UserProfile.objects.get(user__username=username)
    query = request.GET.get('query')
    recipient = None

    if query:
        try:
            recipient = User.objects.get(username=query)
        except User.DoesNotExist:
            pass

    user_profile = UserProfile.objects.get(user=request.user)

    chat_messages_general = ChatMessageGeneral.objects.filter(
        Q(sender_general=request.user, recipient_general=recipient) |
        Q(sender_general=recipient, recipient_general=request.user)
    )

    chat_messages = ChatMessage.objects.filter(
        Q(sender=request.user, recipient=recipient) |
        Q(sender=recipient, recipient=request.user)
    )

    received_senders = ChatMessageGeneral.objects.filter(
        recipient_general=request.user
    ).values_list('sender_general__username', flat=True).distinct()
    
    sent_to_senders = ChatMessageGeneral.objects.filter(
        sender_general=request.user
    ).values_list('recipient_general__username', flat=True).distinct()
    senders = list(set(received_senders) | set(sent_to_senders))

    received_from = ChatMessage.objects.filter(recipient=request.user).values_list('sender__username', flat=True).distinct()
    sent_to = ChatMessage.objects.filter(sender=request.user).values_list('recipient__username', flat=True).distinct()
    unique_chat_partners = list(set(received_from) | set(sent_to))

    combined_senders = list(set(senders) | set(unique_chat_partners))
    context = {
        'user_profile': user_profile,
        'chat_messages_general': chat_messages_general,
        'chat_messages': chat_messages,
        'query': query,
        'recipient': recipient,
        'username': username,
        'combined_senders': combined_senders,
    }
    
    return render(request, 'general_chat_mobile.html', context)

chat_general/templates/chat_konkretny.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans "Chat Interface" %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 0;
        }

        .chat-container {
            max-width: 600px;
            margin: 50px auto;
            border: 1px solid #e0e0e0;
            background-color: #fff;
            border-radius: 10px;
            overflow: hidden;
        }

        .chat-header {
            display: flex;
            align-items: center;
            padding: 10px 20px;
            background-color: #007BFF;
            color: white;
        }

        .chat-header .back-arrow {
            display: inline-block;
            padding: 5px;
            cursor: pointer;
        }

        .chat-content {
            padding: 20px;
            max-height: 400px;
            overflow-y: auto;
        }

        .chat-message {
            display: flex;
            align-items: start;
            margin-bottom: 20px;
        }

        .chat-message img {
            width: 40px;
            height: 40px;
            border-radius: 50%;
            margin-right: 10px;
        }

        .chat-message .message-content {
            padding: 10px 15px;
            border-radius: 10px;
            max-width: 80%;
            position: relative;
        }

        .chat-message .nickname {
            font-weight: bold;
            margin-bottom: 5px;
        }

        .chat-message.sender .message-content {
            background-color: #007BFF;
            color: white;
            align-self: flex-end;
        }

        .chat-message.receiver .message-content {
            background-color: #e0e0e0;
        }

        .chat-footer {
            padding: 20px;
            background-color: #e0e0e0;
            display: flex;
        }

        .chat-footer textarea {
            flex: 1;
            padding: 10px;
            border: none;
            border-radius: 10px;
            resize: none;
        }

        .chat-footer button {
            padding: 10px 20px;
            margin-left: 10px;
            background-color: #007BFF;
            color: white;
            border: none;
            border-radius: 10px;
            cursor: pointer;
        }
    </style>
</head>

<body>
    <div class="chat-container">
        <div class="chat-header">
            <div class="back-arrow">&larr;</div>
            Chat
        </div>

        <div class="chat-content">
            <!-- Example Sender Message -->
            <div class="chat-message sender">
                <img src="sender_profile.jpg" alt="Sender Profile Picture">
                <div class="message-content">
                    <div class="nickname">Sender</div>
                    Hello! How are you?
                </div>
            </div>

            <!-- Example Receiver Message -->
            <div class="chat-message receiver">
                <img src="receiver_profile.jpg" alt="Receiver Profile Picture">
                <div class="message-content">
                    <div class="nickname">Receiver</div>
                    I'm good! Thanks for asking.
                </div>
            </div>
        </div>

        <div class="chat-footer">
            <textarea placeholder="Type a message..."></textarea>
            <button>Send</button>
        </div>
    </div>
</body>

</html>

chat_general/templates/general_chat.html
{% extends 'polozka_new.html' %}
{% load static i18n %}
{% load custom_filters %}
{% block extra_css_zobrazenie %}
    <link href="{% static 'css/general_chat.css' %}" rel="stylesheet">
{% endblock %}

{% block polozka %}
  <div class="chat-general-container">
    <div class="chat-sidebar-container">
      <div class="chat-sidebar">
        <div class="search-form-containerx">
          <form method="GET" action="{% url 'chat_general:user_chat_general' username=username %}" class="search-form-general">
            <div class="search-container-chat">
              <input type="text" placeholder="{% trans 'Search usernames...' %}" name="query" class="search-input" value="{% if query %}{{ query }}{% endif %}">
              <button type="submit" class="search-btn">{% trans "Search" %}</button>
            </div>
          </form>
        </div>
        <!-- Sidebar content -->
        <h2>{% trans "Your Chats" %}</h2>
        <ul class="chat-list">
          {% for chat_user in combined_senders %}
            {% if chat_user != request.user.username %}
              <!-- Desktop Link: Visible on screens wider than 600px -->
              <a href="?query={{ chat_user }}" class="desktop-link">
                <li class="chat-list-item {% if chat_user == query %}active{% endif %}">
                  {{ chat_user }}
                </li>
              </a>
  
              <!-- Mobile Link: Visible on screens narrower than 600px -->
              <a href="{% url 'chat_general:chat_general_mobile_with_sender' username=username sender=chat_user %}?query={{ chat_user }}" class="mobile-link">
                <li class="chat-list-item {% if chat_user == query %}active{% endif %}">
                  {{ chat_user }}
                </li>
              </a>
            {% endif %}
          {% endfor %}
          {% if chat_user %}
            <p>{% trans "No chats found." %}</p>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="chat-main-content">
      {% if recipient %}
        <div class="chat-area">
          <div class="chat-container">
            <div class="recipient-username">
              {% if recipient %}
                {% trans "Chatting with: " %}<a class="product-info-pouzivatel" href="{% url 'user_profile:user_profile' username=recipient.username %}" target="_blank">{{ recipient.username }}</a>
              {% endif %}
            </div>
            <div class="chats-users">
              {% for item in all_messages %}
                {% if item.type == "chat" %}
                  <div class="chat-bubble {% if item.message.sender == request.user %}right{% else %}left{% endif %}">
                      <p class="chat-bubble-mess">{{ item.message.content }}</p>
                  </div>
                {% else %}
                  <div class="chat-bubble {% if item.message.sender_general == request.user %}right{% else %}left{% endif %}">
                      <p class="chat-bubble-mess">{{ item.message.content_general }}</p>
                  </div>
                {% endif %}
              {% endfor %}
            </div>
            <div class="input-container">
              <form method="post" action="{% url 'chat_general:send_message_in_general_chat' username=username sender=query %}" class="obsah-input-form">
                {% csrf_token %}
                <input class="obsah-input" type="text" name="message" placeholder="{% trans 'Type your message...' %}">
                <button class="obsah-input-button" type="submit">{% trans "Send" %}</button>
              </form>
            </div>
          </div>
        </div>
      {% else %}
        <div class="spacer">
          
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

chat_general/templates/general_chat_mobile.html
{% extends 'polozka_new.html' %}
{% load static i18n %}
{% load custom_filters %}
{% block extra_css_zobrazenie %}
    <link href="{% static 'css/general_chat_mobile.css' %}" rel="stylesheet">
{% endblock %}

{% block polozka %}
  <div class="chat-general-container">
    
    <div class="chat-main-content">
        <div class="chat-area">
          <div class="chat-container">
            <div class="recipient-username">
                <a href="{% url 'chat_general:user_chat_general' username=username %}" class="arrow-container">
                    <div class="back-arrow"></div>
                </a>
                <div class="recipient-info">
                    {% if recipient %}
                        {% trans "Chat:" %}
                        <a class="product-info-pouzivatel" href="{% url 'user_profile:user_profile' username=recipient.username %}" target="_blank">{{ recipient.username }}</a>
                    {% endif %}
                </div>
            </div>
            <div class="chats-users">
              {% for message_general in chat_messages_general %}
                {% if message_general.content_general %}
                    <div class="chat-bubble {% if message_general.sender_general == request.user %}right{% else %}left{% endif %}">
                        <p class="chat-bubble-mess">{{ message_general.content_general }}</p>
                    </div>
                {% endif %}
              {% endfor %}
            </div>
            <div class="input-container">
              <form method="post" action="{% url 'chat_general:send_message_in_general_chat' username=username sender=query %}" class="obsah-input-form">
                {% csrf_token %}
                <input class="obsah-input" type="text" name="message" placeholder="{% trans 'Type your message...' %}">
                <button class="obsah-input-button" type="submit">{% trans "Send" %}</button>
              </form>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}