add_product_main/urls.py
from add_product_main import views as add_product_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = 'add_product_main'

urlpatterns = [
    path('<str:username>/polozka/pridanie/', add_product_views.pridaj_polozku, name='user_pridaj_polozku'),
    path('<str:username>/doprava/pridanie/delete/<int:transport_id>/', add_product_views.delete_transport, name='user_delete_transport'),
    path('<str:username>/transportloc/<int:transportloc_id>/delete/', add_product_views.delete_transport_loc, name='delete_transport_loc'),
    path('<str:username>/doprava/<str:nazov_produktu>/select/<int:transport_id>/', add_product_views.select_transport, name='user_select_transport'),
    path('<str:username>/doprava/<str:nazov_produktu>/deselect/<int:transport_id>/', add_product_views.deselect_transport, name='user_deselect_transport'),
    path('<str:username>/doprava/pridanie/', add_product_views.pridaj_dopravu, name='user_pridaj_dopravu'),
    path('<str:username>/polozka/<str:nazov_produktu>/', add_product_views.zobraz_polozku, name='user_zobraz_polozku'),
    path('<str:username>/polozka/<str:nazov_produktu>/<int:anchor>/', add_product_views.zobraz_polozku, name='user_zobraz_polozku'),
    path('<str:username>/polozka/<str:nazov_produktu>/delete/<int:cena_id>/', add_product_views.delete_cena, name='user_delete_cena'),
    path('<str:username>/delete_picture/<int:product_id>/', add_product_views.delete_picture, name='delete_picture'),
    path('<str:username>/polozka/<str:nazov_produktu>/add_picture/', add_product_views.add_picture, name='add_picture'),
] 

# Add the following line to handle media files
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
#api/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import ClusterAPIView, UserLocationsViewSet, StateProvincePobockaCountViewSet

app_name = 'api'

router = DefaultRouter()
router.register(r'locations', UserLocationsViewSet, basename='locations')
router.register(r'regions', StateProvincePobockaCountViewSet, basename='state-province-count')

urlpatterns = [
    path('', include(router.urls)),
    path('clusters/', ClusterAPIView.as_view(), name='cluster-api'),  # Use path directly
]

chat_polozka/urls.py
from django.urls import path

from . import views

app_name = 'chat_polozka'

urlpatterns = [
    path('<str:username>/polozka/<str:nazov_produktu>/chat/', views.chat, name='chat'),
    path('<str:username>/polozka/<str:nazov_produktu>/send_message/', views.send_message_in_polozka, name='send_message_in_polozka'),
]

farmeris/urls.py
#farmeris/urls.py

from allauth.account.views import EmailView
from allauth.account.views import email as allauth_email_view
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.utils.decorators import method_decorator
from django.views.generic import RedirectView
from django.views.i18n import set_language
from email_verification.decorators import email_verification_required
from email_verification.views import CustomEmailView
from login_app import views as login_views
from login_app.views import CustomConfirmEmailView


@method_decorator(email_verification_required, name='dispatch')
class ProtectedEmailView(EmailView):
    pass

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('set_language/', set_language, name='set_language'),
    path('handle_unverified_email/', login_views.handle_unverified_email, name='handle_unverified_email'),
    re_path(r'^account/confirm-email/(?P<key>[-:\w]+)/$', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    path('accounts/resend-confirmation/', login_views.resend_confirmation_email, name='resend_confirmation_email'),
    # path('accounts/email/', email_verification_required(allauth_email_view), name='account_email'),
    path('accounts/email/', login_required(ProtectedEmailView.as_view()), name='account_email'),
    path('email-verification/', include('email_verification.urls')),
    #path('register/', login_views.register, name='register'),
    #path('mapka/', login_views.mapka, name='mapka'),
    #path('login/', login_views.login, name='login'),
    path('privacy-policy/', login_views.privacy_policy, name='privacy_policy'),
    path('accounts/', include('allauth.urls')),
    # path('', RedirectView.as_view(url='/main/')), # root URL redirect
    path('', include('main.urls')),
    path('', include('texts.urls', namespace='texts')),
    path('', include('notes.urls', namespace='notes')),
    path('', include('search.urls', namespace='search')),
    path('', include('map.urls', namespace='map')),
    path('', include('tagmanager.urls', namespace='tagmanager')),
    path('', include('login_app.urls', namespace='login_app')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include('user_profile.urls', namespace='user_profile')),
    path('', include('add_product_main.urls', namespace='add_product_main')),
    path('', include('edit_profile.urls', namespace='edit_profile')),
    path('', include('chat_polozka.urls', namespace='chat_polozka')),
    path('', include('obrazky.urls', namespace='obrazky')),
    path('', include('chat_general.urls', namespace='chat_general')),
    path('email-verification/', include('email_verification.urls')),
    # URL pattern for serving static files in development
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_app/urls.py
# login_app/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from login_app.views import set_username

app_name = 'map'

urlpatterns = [
    path('accounts/set/username/', set_username, name='set_username'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
]

map/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from map import views

app_name = 'map'

urlpatterns = [
    path('map/', views.show_map, name='show_map'),
]

search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from search import views as search_views

app_name = 'search'

urlpatterns = [
    path('search/', search_views.search, name='user_search'),
    path('search/users/', search_views.search2, name='user_search2'),
]

chat_polozka/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class ChatMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_sender')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='message_receiver', default=None)
    content = models.TextField()
    polozka = models.ForeignKey('add_product_main.Polozka', on_delete=models.CASCADE, related_name='chat_messages', null=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.content

add_product_main/views.py
#add_product_main/views.py

import os
import uuid
from decimal import Decimal

from add_product_main.forms import (CenaForm, PictureForm, PolozkaForm,
                                    TransportForm)
from add_product_main.models import (AdditionalImage, Availability, Cena,
                                     Polozka, PolozkaPobocka, PolozkaTransport,
                                     Transport, TransportLoc, PolozkaTag)
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.files.storage import FileSystemStorage
from tagmanager.models import Tag
from django.db import transaction
from django.db.models import Prefetch
from django.http import (Http404, HttpResponse, HttpResponseBadRequest,
                         HttpResponseRedirect)
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseBadRequest
from django.template.defaultfilters import slugify
from djmoney.money import Money
from edit_profile.forms import Pobocka, PobockaForm
from login_app.models import UserProfile
from PIL import Image
from user_profile.forms import UserProfileForm
from decimal import Decimal, InvalidOperation

from .utils import is_valid_image


# Create your views here.
def is_valid_image(file):
    #Check if the given file is a valid image.
    try:
        # Open the image file using Pillow
        image = Image.open(file)
        image.verify()  # Verify if it's a valid image
        return True
    except:
        return False

@login_required
def pridaj_polozku(request, username):
    user_profile = get_object_or_404(UserProfile, user__username=username)
    user_tags = Tag.objects.filter(tagged_profiles__user_profile=user_profile)
    general_tags = Tag.objects.exclude(id__in=user_tags.values_list('id', flat=True))
    transportloc_list = TransportLoc.objects.filter(user_profile=user_profile)
    transport_list = Transport.objects.filter(user_profile=user_profile)
    pobocky = Pobocka.objects.filter(user_profile=user_profile)

    context = {
            'username': username,
            'pobocky': pobocky,
            'user_tags': user_tags,
            'general_tags': general_tags,
            'user_profile': user_profile,
            'transport_list': transport_list,
            'transportloc_list': transportloc_list,
        }

    if request.user != user_profile.user:
        return render(request, 'access_denied.html')

    unit = None
    money_instance = None
    price_amount = '0'
    transport_currency = user_profile.preferred_currency

    #if 'nazov_produktu' in request.method == 'POST':
    if request.method == 'POST':
        nazov_produktu = request.POST['nazov_produktu']
        info_nazov_produktu = request.POST.get('info_nazov_produktu', '')
        info_produktu = request.POST['info_produktu']
        image_file = request.FILES.get('image', None)
        # not optional cena setup
        # amount = request.POST['amount']
        # unit = request.POST['unit']
        # price = request.POST['price']
        # currency = request.POST['currency']
        # currently using optional cena setup
        amount = request.POST.get('amount', None)
        unit = request.POST.get('unit', None)
        price_amount = request.POST.get('price', '0')
        # If 'amount' is not provided, ensure all related fields are set to None
        associate_all_pobocky = 'select_individual' not in request.POST

        if price_amount:
            try:
                # Try converting the price_amount to Decimal to check validity
                Decimal(price_amount)
                if amount:
                    # Only create a Money instance if amount is also provided
                    money_instance = Money(price_amount, user_profile.preferred_currency)
            except InvalidOperation:
                # Handle the case where price_amount is not a valid decimal
                return HttpResponseBadRequest("Invalid price format, please enter a valid number.")

        # Create the transport instance
        transport_type = request.POST.get('transport_type')  
        transport_price = request.POST.get('transport_price')
        transport_unit = request.POST.get('unit')
        transport_amount = request.POST.get('transport_amount')
        transport_notes = request.POST.get('transport_notes', '')

        if transport_price:
            transport_money = Money(transport_price, user_profile.preferred_currency)
        else:
            transport_money = None

        # Extract availability details
        availability_start_date = request.POST.get('availability_start_date', None)
        availability_end_date = request.POST.get('availability_end_date', None)
        available_until_out_of_stock = request.POST.get('available_until_out_of_stock') == 'on'  # assuming it's a checkbox
        raw_stock_count = request.POST.get('stock_count', '9999')
        stock_count = int(raw_stock_count) if raw_stock_count.strip() else 9999

        #JS
        required_fields = ['nazov_produktu', 'info_produktu'] #'amount', 'unit', 'price', 'currency', 'transport_type'
        missing_fields = [field for field in required_fields if not request.POST.get(field)]
        if missing_fields:
            missing_fields_str = ', '.join(missing_fields)
            return HttpResponseBadRequest(f"Missing required fields: {missing_fields_str}.")

        # Check file extension
        if image_file and not any([image_file.name.lower().endswith(ext) for ext in ['.jpg', '.jpeg', '.png', '.gif']]):
            return HttpResponseBadRequest("Invalid file extension.")

        # Validate the content type
        valid_content_types = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']
        if image_file and image_file.content_type not in valid_content_types:
            return HttpResponseBadRequest("Unsupported file type.")

        # Use Pillow to check if it's a valid image
        if image_file and not is_valid_image(image_file):
            return HttpResponseBadRequest("Invalid image file.")
        
        if not (nazov_produktu and info_produktu): #and amount and unit and price and currency and info_produktu and transport_type
            return HttpResponseBadRequest("Missing required fields.")
        
        existing_product = Polozka.objects.filter(user_profile=user_profile, nazov_produktu=nazov_produktu).exists()
        if existing_product:
            return HttpResponseBadRequest("A product with the same name already exists for this user.")
        
        product = Polozka.objects.create(
            user_profile=user_profile,
            nazov_produktu=nazov_produktu,
            info_nazov_produktu=info_nazov_produktu,
            info_produktu=info_produktu,
            image=image_file,
            associate_all_pobocky=associate_all_pobocky,
        )

        # Handle Tag associations directly
        user_tags_ids = request.POST.getlist('user_tags')
        general_tags_ids = request.POST.getlist('general_tags')
        all_tag_ids = user_tags_ids + general_tags_ids
        for tag_id in all_tag_ids:
            tag = Tag.objects.get(id=tag_id)
            PolozkaTag.objects.create(polozka=product, tag=tag)

        # Handle association with Pobocky
        if associate_all_pobocky:
            # Associate this Polozka with all current Pobocky
            all_pobocky = Pobocka.objects.filter(user_profile=user_profile)
            for pobocka in all_pobocky:
                PolozkaPobocka.objects.create(polozka=product, pobocka=pobocka)
        else:
            # Associate only with selected Pobocky
            selected_pobocky_ids = request.POST.getlist('pobocka_location')  # Assuming this is how you named your field
            selected_pobocky = Pobocka.objects.filter(id__in=selected_pobocky_ids, user_profile=user_profile)
            for pobocka in selected_pobocky:
                PolozkaPobocka.objects.create(polozka=product, pobocka=pobocka)

        if amount and unit and money_instance:
            cena = Cena.objects.create(
                user_profile=user_profile,
                polozka=product,
                amount=amount,
                unit=unit,
                price=money_instance
            )
        # Create the Availability instance
        if availability_start_date or availability_end_date or available_until_out_of_stock or stock_count:
            availability = Availability.objects.create(
                user_profile=user_profile,
                polozka=product,
                availability_start_date=availability_start_date if availability_start_date else None,
                availability_end_date=availability_end_date if availability_end_date else None,
                available_until_out_of_stock=available_until_out_of_stock,
                stock_count=stock_count
            )
        # Check if the necessary transport fields are filled
        create_transport_loc = transport_type and transport_price and transport_unit and transport_amount and transport_currency

        if create_transport_loc:
            existing_transport_loc = TransportLoc.objects.filter(
                user_profile=user_profile,
                polozka=product,
                transport_type=transport_type,
                price=transport_money,
                unit=transport_unit,
                amount=transport_amount,
                transport_notes=transport_notes
            ).first()

            if existing_transport_loc:
                # If an existing transport with the same parameters is found, use it
                transport_loc = existing_transport_loc
            else:
                # If not, create a new transport instance
                transport_loc = TransportLoc.objects.create(

add_product_main/templates/2polozka_cena_pridanie.html
{% load i18n %}

<div class="price">
  <label for="price">{% trans "Price:" %}</label>
  <div class="input-wrapper-dop">
    <input type="number" id="price" min="0" placeholder="{% trans 'Price:' %}" name="price" step="0.01">
    <div id="currency" name="currency" class="unit-dop mar">
      {{ user_profile.preferred_currency }}
    </div>
  </div>
  <label for="amount">{% trans "Amount:" %}</label>

  <div class="input-wrapper-dop">
    <input type="number" id="amount" name="amount" min="0" value="1">
    <!--<label for="unit">Jednotka:</label>-->
    <select id="unit" name="unit" class="unit-dop">
      <option value="kg">kg</option>
      <option value="ks">ks</option>
      <option value="g">g</option>
      <option value="l">{% trans "liter" %}</option>
    </select>
  </div>
  {% if cena_add %}
    <div class="deselect-button-container">
        <button type="submit" name="action" value="add_cena" for="cena-add" class="cena-add add-button-icon-submit">
            <div class="plus-icon"></div>
        </button>
    </div>
  {% endif %}

</div>

add_product_main/templates/2polozka_doprava_pridanie.html
{% load i18n %}

<div class="transport">
  <label for="transport_type" class="doprava-first">{% trans "Transport type:" %}</label>
  <select id="transport_type" name="transport_type">
    <option value="online">{% trans "Online" %}</option>
    <option value="kurier">{% trans "Courier" %}</option>
    <option value="vlastne">{% trans "Custom" %}</option>
  </select>
  <textarea class="transport_notes" id="transport_notes" name="transport_notes" placeholder="{% trans 'Enter notes' %}"></textarea>

  <label for="transport_price">{% trans "Price:" %}</label>
  <div class="input-wrapper-dop">
    <input type="number" id="transport_price" name="transport_price" min="0" placeholder="{% trans 'Transport price' %}" step="0.01">
    <div id="currency" name="currency" class="currency-dop mar">
      {{ user_profile.preferred_currency }}
    </div>
  </div>
  
  <label for="unit">{% trans "Amount:" %}</label>
  <div class="input-wrapper-dop">
    <input type="number" id="transport_amount" name="transport_amount" min="0" placeholder="{% trans 'Till' %}" step="0.0001">
    <select id="unit" name="unit" class="unit-dop">
      <option value="kg">kg</option>
      <option value="ks">ks</option>
      <option value="g">g</option>
      <option value="l">{% trans "liter" %}</option>
    </select>
  </div>
  {% if transport_add %}
    <!-- Add a hidden field to store the transport_id -->
    <input type="hidden" name="transport_id" value="{{ transport.id }}">
    
    <button for="transport-add" class="transport-add cena-add add-button-icon-submit">
    <div class="plus-icon"></div>
    </button>
  {% endif %}
</div>

add_product_main/templates/add_picture.html
{% load static i18n %}

<link href="{% static 'css/add_picture.css' %}" rel="stylesheet" media="screen">
<link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

<div class="container">
    {% blocktrans with item_name=polozka.nazov_produktu %}
		<h2>Add Picture to "{{ item_name }}"</h2>
	{% endblocktrans %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-buttons">
            <button type="submit">{% trans "Save Changes" %}</button>
            <a href="{% url 'add_product_main:user_zobraz_polozku' username=polozka.user_profile.user.username nazov_produktu=polozka.nazov_produktu %}">{% trans "Discard Changes" %}</a>
        </div>
    </form>
</div>

add_product_main/templates/cena_delete.html
<form method="POST" action="{% url 'add_product_main:user_delete_cena' username=user_profile.user.username nazov_produktu=polozka.nazov_produktu cena_id=cena.id %}">
    {% csrf_token %}
    {% include "icons/minus_submit.html" %}
</form>

add_product_main/templates/doprava_pridanie.html
{% extends 'polozka_new.html' %}
{% load static i18n %}

{% block extra_css_doprava %}
  <link href="{% static 'css/doprava_pridanie3.css' %}" rel="stylesheet">
  <!--
       <link href="{% static 'css/doprava_pridaniex.css' %}" rel="stylesheet">
       <link href="{% static 'css/doprava_pridanie2.css' %}" rel="stylesheet">
  -->
{% endblock %}

{% block polozka %}

  <div class="doprava-header">
    <h1 class="doprava-h2">{% trans "Input transport option" %}</h1>
  </div>
  <a class="edit_user_profile-a-d" href="{% url 'user_profile:user_profile' username=user_profile.user.username %}"><button class="edit_user_profile2-d">{% trans "Back to the profile" %}</button></a>
  <div class="adding-transport-container">

    <div class="doprava-display-container-holder">
      <div class="doprava-display-container">
        {% include 'transports_display.html' %}
        <a href="{% url 'edit_profile:add_pobocka' username=username %}" class="adjust-settings-button" target=_blank>
          <button type="button">{% trans "Adjust Settings" %}</button>
        </a>
      </div>
    </div>

    {% include 'doprava_pridanie_display.html' with deleting_items=True selecting_items=False show_checkbox=False%}
    <form method="post" class="doprava-input-form" action="{% url 'add_product_main:user_pridaj_dopravu' username=user_profile.user.username %}">
      {% csrf_token %}

      <div class="main-transport">
        {% include '2polozka_doprava_pridanie.html' with transport_add=True %}
      </div>

    </form>
  </div>
{% endblock %}

add_product_main/templates/polozka_new.html
{% extends 'polozka.html' %}
{% load static i18n %}

{% block polozka_new %}
  {% include 'sidebar.html' %}

  {% include 'sidebar-btn.html' %}
  <div class="green-main-bg" id="1">
    <div class="blue-main-bg">
      {% block polozka %}{% endblock %}
    </div>
  </div>
  <footer>
    {% include 'footer_content.html' %}
  </footer>

{% endblock %}

add_product_main/templates/sidebar.html
<!-- sidebar.html-->

{% load i18n %}
{% load custom_filters %}
{% load static %}
{% load uuid_username_tag %}

<!-- Stylesheets -->
{% if sidebar_visible %}
    <link href="{% static 'css/sidebar2.css' %}" rel="stylesheet" media="screen">
{% else %}
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet" media="screen">
{% endif %}
<link href="{% static 'css/sidebar_mobile.css' %}" rel="stylesheet" media="screen">

<!-- In the future redesign as login_app/middlewares.py sidebar_visible cos this logic sucks -->
{% if user.is_authenticated %}
  {% if user.userprofile.theme == 'dark' %}
    <link rel="stylesheet" href="{% static 'css/dark-theme.css' %}">
  {% else %}
    <link rel="stylesheet" href="{% static 'css/light-theme.css' %}">
  {% endif %}
{% else %}
  {% if theme == 'dark' %}
    <link rel="stylesheet" href="{% static 'css/dark-theme.css' %}">
  {% else %}
    <link rel="stylesheet" href="{% static 'css/light-theme.css' %}">
  {% endif %}
{% endif %}

<!-- Sidebar Content -->
<label class="mobile-side-container">
  <input type="checkbox" class="mobile-checkbox">
  <span class="menu"> <span class="hamburger"></span> </span>

  <nav class="sidebar">
    <div class="sidebar-mobile-left">
      {% include 'user_profile_display.html' %}
      <div class="sidebar-menu-content3">
        {% include 'sidebar_menu.html' %}
      </div>
    </div>
    <!-- Navigation links -->
    <div class="sidebar-butt-container">
      <div class="sidebar-butt-widget">
        <ul>
          {% if request.user.username|is_uuid_username %}
            <li>
              <a class="sidebar-button-a" href="{% url 'login_app:set_username' %}">
                <span class="sidebar-button-a-ti-container"><i class="ti ti-user-edit"></i><span class="sidebar-button-a-text">{% trans "Set username" %}</span></span>
              </a>
            </li>
          {% endif %}
          <li>
            <a class="sidebar-button-a {% if current_view_name == 'main' %}focused{% endif %}" href="{% url 'main:main' %}">
              <span class="sidebar-button-a-ti-container"><i class="ti ti-home"></i><span class="sidebar-button-a-text">{% trans "Home" %}</span></span>
            </a>
          </li>
          <li>
            <a class="sidebar-button-a {% if current_view_name == 'map' %}focused{% endif %}" href="{% url 'map:show_map' %}">
              <span class="sidebar-button-a-ti-container"><i class="ti ti-map-pin-search"></i><span class="sidebar-button-a-text">{% trans "Map" %}</span></span>
            </a>
          </li>
          <li>
            <a class="sidebar-button-a {% if current_view_name == 'search' %}focused{% endif %}" href="{% url 'search:user_search' %}">
              <span class="sidebar-button-a-ti-container"><i class="ti ti-search"></i><span class="sidebar-button-a-text">{% trans "Search" %}</span></span>
            </a>
          </li>
          <li>
            <a class="sidebar-button-a {% if current_view_name == 'search2' %}focused{% endif %}" href="{% url 'search:user_search2' %}">
              <span class="sidebar-button-a-ti-container"><i class="ti ti-user-search"></i><span class="sidebar-button-a-text">{% trans "Profiles" %}</span></span>
            </a>
          </li>
          {% if user.is_authenticated %}

            {% comment %}
            <!-- <li>
                 <a class="sidebar-button-a {% if current_view_name == 'chat_general' %}focused{% endif %}" href="{% url 'chat_general:user_chat_general' username=user.username %}">
                 <span><i class="ti ti-messages"></i>  {% trans "Chat" %}</span>
                 </a>
                 </li> -->
            {% endcomment %}

            {% if user.userprofile.is_seller %}
              <li>
                <a class="sidebar-button-a {% if current_view_name == 'user_profile_edit' %}focused{% endif %}" href="{% url 'user_profile:user_profile_edit' username=user.username %}">
                  <span class="sidebar-button-a-ti-container"><i class="ti ti-shopping-cart-plus"></i><span class="sidebar-button-a-text">{% trans "My offers" %}</span></span>
                </a>
              </li>
              <li>
                <a class="sidebar-button-a {% if current_view_name == 'user_pridaj_dopravu' %}focused{% endif %}" href="{% url 'add_product_main:user_pridaj_dopravu' username=user.username %}">
                  <span class="sidebar-button-a-ti-container"><i class="ti ti-truck"></i><span class="sidebar-button-a-text">{% trans "My Transport" %}</span></span>
                </a>
              </li>
            {% endif %}
          {% else %}
            <li>
              <a class="sidebar-button-a" href="{% url 'account_login' %}">
                <span class="sidebar-button-a-ti-container"><i class="ti ti-messages"></i><span class="sidebar-button-a-text">{% trans "Login for more" %}</span></span>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
    
    <!-- Theme switcher form -->
    <div class="sidebar-menu">
      <input type="checkbox" id="menuToggle">
      <label for="menuToggle" class="sidebar-menu-button"><i class="ti ti-settings"></i></label>
      <div class="sidebar-menu-content">
        {% include 'sidebar_menu.html' %}
      </div>
    </div>
  </nav>
</label>

<!-- Scripts -->
{% block extra_js %}
  {% comment %}
  <!-- <script src="{% static 'js/theme_switch.js' %}"></script>
  <script src="{% static 'js/changes-scripts.js' %}"></script>
  <script src="{% static 'js/menu-hide.js' %}"></script> -->
  {% endcomment %}
  <script src="{% static 'js/menu-hide.js' %}"></script>
{% endblock %}

add_product_main/templates/transport_deselect.html
<form method="post" action="{% url 'add_product_main:user_deselect_transport' username=user_profile.user.username transport_id=polozka_transport.transport.id nazov_produktu=nazov_produktu %}">
    {% csrf_token %}
    {% include "icons/minus_submit.html" %}
</form>

add_product_main/templates/transport_select.html
<form method="post" action="{% url 'add_product_main:user_select_transport' username=user_profile.user.username transport_id=transport.id nazov_produktu=nazov_produktu %}">
    {% csrf_token %}
    {% include "icons/plus_submit.html" %}
</form>