api/urls.py
#api/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import ClusterAPIView, UserLocationsViewSet, StateProvincePobockaCountViewSet

app_name = 'api'

router = DefaultRouter()
router.register(r'locations', UserLocationsViewSet, basename='locations')
router.register(r'regions', StateProvincePobockaCountViewSet, basename='state-province-count')

urlpatterns = [
    path('', include(router.urls)),
    path('clusters/', ClusterAPIView.as_view(), name='cluster-api'),  # Use path directly
]

farmeris/urls.py
#farmeris/urls.py

from allauth.account.views import EmailView
from allauth.account.views import email as allauth_email_view
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path, re_path
from django.utils.decorators import method_decorator
from django.views.generic import RedirectView
from django.views.i18n import set_language
from email_verification.decorators import email_verification_required
from email_verification.views import CustomEmailView
from login_app import views as login_views
from login_app.views import CustomConfirmEmailView


@method_decorator(email_verification_required, name='dispatch')
class ProtectedEmailView(EmailView):
    pass

urlpatterns = [
    path('admin-panel/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('set_language/', set_language, name='set_language'),
    path('handle_unverified_email/', login_views.handle_unverified_email, name='handle_unverified_email'),
    re_path(r'^account/confirm-email/(?P<key>[-:\w]+)/$', CustomConfirmEmailView.as_view(), name='account_confirm_email'),
    path('accounts/resend-confirmation/', login_views.resend_confirmation_email, name='resend_confirmation_email'),
    # path('accounts/email/', email_verification_required(allauth_email_view), name='account_email'),
    path('accounts/email/', login_required(ProtectedEmailView.as_view()), name='account_email'),
    path('email-verification/', include('email_verification.urls')),
    #path('register/', login_views.register, name='register'),
    #path('mapka/', login_views.mapka, name='mapka'),
    #path('login/', login_views.login, name='login'),
    path('privacy-policy/', login_views.privacy_policy, name='privacy_policy'),
    path('accounts/', include('allauth.urls')),
    # path('', RedirectView.as_view(url='/main/')), # root URL redirect
    path('', include('main.urls')),
    path('', include('texts.urls', namespace='texts')),
    path('', include('notes.urls', namespace='notes')),
    path('', include('search.urls', namespace='search')),
    path('', include('map.urls', namespace='map')),
    path('', include('tagmanager.urls', namespace='tagmanager')),
    path('', include('login_app.urls', namespace='login_app')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('', include('user_profile.urls', namespace='user_profile')),
    path('', include('add_product_main.urls', namespace='add_product_main')),
    path('', include('edit_profile.urls', namespace='edit_profile')),
    path('', include('chat_polozka.urls', namespace='chat_polozka')),
    path('', include('obrazky.urls', namespace='obrazky')),
    path('', include('chat_general.urls', namespace='chat_general')),
    path('email-verification/', include('email_verification.urls')),
    # URL pattern for serving static files in development
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main, name='main'),
]

map/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

from map import views

app_name = 'map'

urlpatterns = [
    path('map/', views.show_map, name='show_map'),
]

search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from search import views as search_views

app_name = 'search'

urlpatterns = [
    path('search/', search_views.search, name='user_search'),
    path('search/users/', search_views.search2, name='user_search2'),
]

texts/urls.py
# texts/urls.py

from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from texts import views

app_name = 'texts'

urlpatterns = [
    path('raw_milk_manifesto/', views.manifesto, name='manifesto'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('tutorial/', views.uncoded, name='tutorial'),
    path('thank-you/', views.thanks, name='thank_you'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from datetime import datetime

import pytz
from add_product_main.models import Polozka
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import QueryDict
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from login_app.models import UserProfile


def main(request):

    if request.user.is_authenticated:
        user_profile = UserProfile.objects.get(user=request.user)
        filter_trusted = user_profile.filter_trusted
    else:
        user_profile = None
        filter_trusted = True

    #all_products = Polozka.objects.all()
    query = request.GET.get('query')

    if query:
        base_query = Polozka.objects.filter(
            Q(nazov_produktu__icontains=query) |
            Q(user_profile__user__username__icontains=query)
        )
        if filter_trusted:
            # Filter to only show products from trusted users
            all_products = base_query.filter(user_profile__is_trusted=True)
        else:
            all_products = base_query
    else:
        if filter_trusted:
            # Show only products from trusted users
            all_products = Polozka.objects.filter(user_profile__is_trusted=True)
        else:
            # Show all products
            all_products = Polozka.objects.all()
            all_products = all_products.order_by('-created_at')

    #pagination
    if request.user.is_authenticated:
        default_pagination = user_profile.pagination_preference
    else:
        default_pagination = 10  # or any default value you want for non-logged in users

    items_per_page = int(request.GET.get('items_per_page', default_pagination))

    paginator = Paginator(all_products, items_per_page)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    #saved pagination for user
    if request.user.is_authenticated and items_per_page != default_pagination:
        user_profile.pagination_preference = items_per_page
        user_profile.save()
        #end of pagination

    # Preserve the query parameter in the pagination links
    query_params = QueryDict(mutable=True)
    if query:
        query_params['query'] = query

    context = {
        'products': products,
        'user_profile': user_profile,
        'items_per_page': items_per_page,
        'query_params': query_params.urlencode(),
        'current_view_name': 'main',
    }
    return render(request, 'main.html', context)

main/templates/main.html
{% extends 'polozka_new.html' %}
{% load static i18n %}
{% load custom_filters %}

{% block extra_css_polozka %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/main_mobile.css' %}" rel="stylesheet">
    <link href="{% static 'css/search2.css' %}" rel="stylesheet">
    <link href="{% static 'css/polozka_profile_view.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/polozka_profile_view2.css' %}" rel="stylesheet" media="screen">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Uni+Sans:wght@400;700&display=swap" rel="stylesheet">
    <!-- uni sans font link -->
{% endblock %}

{% block polozka %}
    {% comment %}
    {% include 'search_header_search_bar.html' %}
    {% endcomment %}
    {% include 'main_menu.html' %}

    <div class="main-container">
        <h1><img src="/static/media/Farmeris_png_final.png" alt="Farmeris Logo">Farmeris</h1>
        <!-- <h3>farmeris-sk@proton.me</h3> -->
    </div>
    <!-- <div class="recommended-product">
         <div class="">
         <p>Odporucane polozky</p>
         </div>
         </div> -->
    <!--
         <div class="recommended-farm">
         <p>Odporucana farma</p>
         </div>
         {% comment %}
         {% for product in products %}
         {% include 'polozka_profile_view.html' with username=request.user.username nazov_produktu=product.nazov_produktu polozka=product %}
         {% endfor %}
         {% endcomment %}

    -->
{% endblock %}

main/templates/main_menu.html
{% load static i18n %}

{% block extra_css_zobrazenie %}
    <link href="{% static 'css/main_menu.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'css/main_menu_mobile.css' %}" rel="stylesheet" media="screen">
{% endblock %}

<div class="header-bar">
    <form method="GET" action="{% url 'search:user_search' %}" class="search-form">
        <input type="text" placeholder="{% trans 'Search..' %}" name="query" class="search-field" value="{{ request.GET.query }}">
        <button type="submit" class="search-button">{% trans 'Search' %}</button>
    </form>

    <!-- Additional buttons next to the search bar -->
    <a href="{% url 'main:main' %}" class="header-menu-btn header-btn {% if current_view_name == 'main' %}hidden{% endif %}">
        <i class="ti ti-home"></i> {% trans 'Home' %}
    </a>
    {% comment %}
    <!-- <a href="{% url 'texts:about' %}" class="header-menu-btn header-btn {% if current_view_name == 'about' %}hidden{% endif %}">
         {% trans 'About' %}
         </a> -->

    <!-- <a href="{% url 'map:show_map' %}" class="header-menu-btn header-btn {% if current_view_name == 'map' %}hidden{% endif %}">
         <i class="ti ti-map-pin"></i> {% trans 'Map' %}
         </a> -->
    {% endcomment %}

    <a href="{% url 'texts:manifesto' %}" class="header-menu-btn header-btn {% if current_view_name == 'manifesto' %}hidden{% endif %}">
        <i class="ti ti-notebook"></i> {% trans 'Manifesto' %}
    </a>
    <a href="{% url 'texts:tutorial' %}" class="header-menu-btn header-btn {% if current_view_name == 'tutorial' %}hidden{% endif %}">
        <i class="ti ti-slideshow"></i> {% trans 'Tutorial' %}
    </a>
    <a href="{% url 'texts:contact' %}" class="header-menu-btn header-btn {% if current_view_name == 'contact' %}hidden{% endif %}">
        <i class="ti ti-mail"></i> {% trans 'Contact' %}
    </a>

    <form method="GET" action="{% url 'search:user_search' %}" class="search-form-mobile">
        <input type="text" placeholder="{% trans 'Search..' %}" name="query" class="search-field" value="{{ request.GET.query }}">
        <button type="submit" class="search-button">{% trans 'Search' %}</button>
    </form>
</div>

main/templates/rec_farm.html
{% load static i18n %}

<link href="{% static 'css/rec_farm.css' %}" rel="stylesheet" media="screen">

<div class="rec_farm_container">
    <!-- <div class="rec_nadpis"><p>Farma</p></div> -->
    <div class="product-pic2">
         {% if polozka.image %}
         <img src="{{ polozka.image.url }}" alt="{{ polozka.nazov_produktu }}">
         {% else %}
         <p>{% trans "No picture available" %}</p>
         {% endif %}
    </div>
</div>